tasks:
  - name: mattermost
    command: "docker compose up -d && bash ./gitpod_init.sh"
  - name: download_model
    command: |
      mkdir -p models
      wget https://gpt4all.io/models/ggml-gpt4all-j.bin -O models/ggml-gpt4all-j
      echo "The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.\n### Prompt:\n{{.Input}}\n### Response:" > models/ggml-gpt4all-j.tmpl

ports:
  - name: mattermost
    port: 8065
    onOpen: open-browser
